[package]
name = "amico-sdk"
version = "0.0.2"
edition = "2024"
description = "The SDK of the Amico AI Agent Framework"
repository = "https://github.com/AIMOverse/amico"
license = "MIT"

[lib]
name = "amico"
path = "src/lib.rs"

[features]
core = ["amico-core"]

[dependencies]
amico-core = { path = "../amico-core", optional = true }
async-trait = "0.1.86"
serde_json = "1.0.138"
thiserror = "2.0.11"
serde = "1.0.217"
tokio = { version = "1.44.2", features = ["rt"] }

[dev-dependencies]
tokio = { version = "1.44.2", features = ["rt", "macros", "time"] }
