[package]
name = "amico-sdk"
version = "0.0.2"
edition = "2021"
description = "The SDK of the Amico AI Agent Framework"
repository = "https://github.com/AIMOverse/amico"
license = "MIT"

[lib]
name = "amico"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.86"
serde_json = "1.0.138"
thiserror = "2.0.11"
amico-core = { path = "../amico-core" }
serde = "1.0.217"

[dev-dependencies]
tokio = { version = "1.43.0", features = ["rt", "macros"] }
