[package]
name = "amico-sdk"
version = "0.1.0"
edition = "2021"
description = "The SDK of the Amico AI Agent Framework"
repository = "https://github.com/AIMOverse/amico"
license = "MIT"

[lib]
name = "amico"
path = "src/lib.rs"

[dependencies]
