[package]
name = "amico-sdk"
version = "0.0.2"
edition = "2024"
description = "The SDK of the Amico AI Agent Framework"
repository = "https://github.com/AIMOverse/amico"
license = "MIT"

[lib]
name = "amico"
path = "src/lib.rs"

[features]
default = ["mcp-client"]
mcp-client = [
    "dep:rig-core",
    "rig-core/mcp",
    "dep:mcp-core",
    "mcp-core/sse",
    "mcp-core-macros",
]

[dependencies]
async-trait = "0.1.86"
serde_json = "1.0.138"
thiserror = "2.0.11"
amico-core = { path = "../amico-core" }
serde = "1.0.217"
tokio = { version = "1.43.0", features = ["rt"] }
rig-core = { version = "0.11.0", optional = true }
mcp-core = { version = "0.1.43", optional = true }
mcp-core-macros = { version = "0.1.11", optional = true }

[dev-dependencies]
tokio = { version = "1.43.0", features = ["rt", "macros", "time"] }
