[package]
name = "amico-cli"
version = "0.1.0"
edition = "2021"
description = "The developer command line interface for the Amico AI Agent Framework"
repository = "https://github.com/AIMOverse/amico"
license = "MIT"

[dependencies]
