[package]
name = "amico-plugins"
version = "0.1.0"
edition = "2021"
description = "The plugins of the Amico AI Agent Framework"
repository = "https://github.com/AIMOverse/amico"
license = "MIT"

[dependencies]
