# The example configuration file of a single-agent runtime

# The name of the agent
name = "AIMO"

# The version of the agent
version = 0

# Standalone runtime using `tokio::main`
runtime = "standalone"

# Plugins enabled
plugins = ["twitter"]

# Event Settings
[event_config]
expiry_time = 10 # Event default expiry time (in seconds)



