[package]
name = "amico-firmware"
version = "0.1.0"
edition = "2021"
description = "The firmware of the Amico AI Agent Framework"
repository = "https://github.com/AIMOverse/amico"
license = "MIT"

[dependencies]
